version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: desafioapiprojeto-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: desafioApiProjeto_db
      MONGO_INITDB_ROOT_USERNAME: desafio_user
      MONGO_INITDB_ROOT_PASSWORD: desafio_pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - desafioapiprojeto-network

  desafioapiprojeto-app:
    build: .               # Usa o Dockerfile presente na raiz do projeto
    container_name: desafioapiprojeto-app
    restart: always
    ports:
      - "8777:8777"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://desafio_user:desafio_pass@mongodb:27017/desafioApiProjeto_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - desafioapiprojeto-network

volumes:
  mongodb_data:

networks:
  desafioapiprojeto-network:
    driver: bridge
